services:
  app:
    build:
    context: .
    dockerfile: Dockerfile
  container_name: cantina
  ports:
    - "1010:1010"
  restart: unless-stopped
  depends_on:
    - db
  env_file:
    - /home/gabriel/Documentos/cantinaDocker:/.env
  command: sh -c "npx prisma migrate deploy && npm run seed && npm run dev"

volumes:
  postgres_data:
